# Generated by Django 3.1.7 on 2021-03-13 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Date_of_Birth',
        ),
        migrations.AddField(
            model_name='user',
            name='Address',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
